version: '3.5'

services:

  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d:z

  node:
    build:
      context: ./.docker/build
    hostname: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app:z
    command:
      - sh
      - -c
      - pm2 start pm2.config.js && tail -f /dev/null